  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ll-leaf1-sw1
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ll-leaf1-sw1 Configuration Update
    ios_config:
      timeout: 60
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ll-leaf1-sw1/files/ll-leaf1-sw1-config.cfg"