  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define YTI Nashville Core Switch
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: YTI Nashville Core Configuration Update
    ios_config:
      timeout: 60
      #lines: hostname Test1
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/nashvillesw1/files/nashvillesw1-config.cfg"