  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ttilgb_mr_b
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ttilgb_mr_b Configuration Update
    ios_config:
      timeout: 60
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ttilgb_mr_b/files/ttilgb_mr_b-config.cfg"