  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define TTI Access Switch
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: TTI Access Switch Configuration Update
    ios_config:
      timeout: 60
      #lines: hostname Test1
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ttilgb-6513a/files/ttilgb-6513a-config.cfg"