  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ttilgb_bgp_rtr1
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ttilgb_bgp_rtr1 Configuration Update
    ios_config:
      timeout: 60
      #lines: hostname Test1
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ttilgb_bgp_rtr1/files/ttilgb_bgp_rtr1-config.cfg"