  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ttilgb_3560_gearship
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ttilgb_3560_gearship Configuration Update
    ios_config:
      timeout: 60
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ttilgb_3560_gearship/files/ttilgb_3560_gearship-config.cfg"