  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ttilgb_dc_9372_a
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ttilgb_dc_9372_a Configuration Update
    ios_config:
      timeout: 60
      #lines: hostname Test1
      provider: "{{ provider }}"
      authorize: yes
      src: "/home/strategic/TTI/ansible/roles/ttilgb_dc_9372_a/files/ttilgb_dc_9372_a-config.cfg"